base: /
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=4'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: de_DE
    iso-639-1: en
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
    websiteTitle: ''
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: ''
    base: /en/
    websiteTitle: ''
    navigationTitle: English
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
rootPageId: 1
routeEnhancers:
  -
    type: PageType
    default: /
    index: ''
    map:
      /: 0
      sitemap.xml: 1533906435
websiteTitle: 'Liszt-Portal v13'
