type: typo3
docroot: public
php_version: "8.2"
webserver_type: nginx-fpm
database: { type: mariadb, version: "10.11" }
composer_version: "2"
nodejs_version: "20"
web_environment:
    - TYPO3_CONTEXT=Development
    - TYPO3_DB_DRIVER=mysqli
    - TYPO3_DB_USERNAME=db
    - TYPO3_DB_PASSWORD=db
    - TYPO3_DB_PORT=3306
    - TYPO3_DB_HOST=db
    - TYPO3_DB_DBNAME=db
    - TYPO3_SETUP_ADMIN_EMAIL=typo3@example.com
    - TYPO3_SETUP_ADMIN_USERNAME=admin
    - TYPO3_SETUP_ADMIN_PASSWORD=Slubadmin.1
    - TYPO3_PROJECT_NAME=TYPO3-Dev
